---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
spec:
  capacity:
    storage: 100Gi  # Adjust size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  mountOptions:
    - hard
    - nfsvers=4
    - nolock
    - rw
  nfs:
    server: 192.168.178.60  # Synology NAS IP
    path: /volume1/Kubernetes/minio  # Synology NAS path (note capital K)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs-pvc
  namespace: minio
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi