---
apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    helm.sh/chart: homepage-2.1.0
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/version: "v1.2.0"
    app.kubernetes.io/managed-by: Helm
    
data:
  bookmarks.yaml: |
    - Developer:
      - Github:
        - abbr: GH
          href: https://github.com/Piotr1215
      - Homelab Repo:
        - abbr: Repo
          href: https://github.com/Piotr1215/homelab
    - Documentation:
      - K8s Docs:
        - abbr: K8s
          href: https://kubernetes.io/docs/
      - ArgoCD Docs:
        - abbr: Argo
          href: https://argo-cd.readthedocs.io/
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Management:
      - ArgoCD:
          description: GitOps Continuous Delivery
          href: http://192.168.178.93
          icon: git.svg
          showStats: true
          widget:
            type: argocd
            url: http://192.168.178.93
      - Portainer:
          description: Container Management Platform
          href: https://192.168.178.96:9443
          icon: portainer.svg
          showStats: true
          widget:
            type: portainer
            url: https://192.168.178.96:9443
            env: 1
            kubernetes: true
    - Observability:
      - Prometheus:
          description: Metrics & Monitoring
          href: http://192.168.178.99:9090
          icon: prometheus.svg
          widget:
            type: prometheus
            url: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090
      - Grafana:
          description: Visualization & Dashboards
          href: http://192.168.178.98
          icon: grafana.svg
          widget:
            type: grafana
            url: http://kube-prometheus-stack-grafana.prometheus.svc.cluster.local:80
            username: admin