---
apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
# Source: homepage/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    helm.sh/chart: homepage-2.1.0
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/version: "v1.2.0"
    app.kubernetes.io/managed-by: Helm
    
data:
  bookmarks.yaml: |
    - Homelab:
      - Github Repo:
        - abbr: GH
          href: https://github.com/Piotr1215/homelab
      - ArgoCD:
        - abbr: Argo
          href: http://192.168.178.93
      - Vault:
        - abbr: Vault
          href: http://192.168.178.92:8200
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Infrastructure:
      - ArgoCD:
          description: GitOps Continuous Delivery
          href: http://192.168.178.93
          icon: argocd.svg
      - Vault:
          description: Secrets Management
          href: http://192.168.178.92:8200
          icon: vault.svg
      - Homepage:
          description: This Dashboard
          href: http://192.168.178.94
          icon: homepage.svg
    - Kubernetes:
      - Control Plane:
          description: kube-main
          href: #
          icon: kubernetes.svg
      - Worker 1:
          description: kube-worker1
          href: #
          icon: kubernetes.svg
      - Worker 2:
          description: kube-worker2
          href: #
          icon: kubernetes.svg
    - Monitoring:
      - External Secrets:
          description: ESO Operator
          href: #
          icon: kubernetes.svg
  settings.yaml: |
    title: Homelab Dashboard
    headerStyle: boxed
    layout:
      Infrastructure:
        style: row
        columns: 3
      Kubernetes:
        style: row
        columns: 3
      Monitoring:
        style: row
        columns: 3
    
  widgets.yaml: |
    - resources:
        backend: resources
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
---
# Source: homepage/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/service: homepage
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homepage
    app.kubernetes.io/version: v1.2.0
    helm.sh/chart: homepage-2.1.0
  annotations:
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/name: homepage
---
# Source: homepage/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homepage
    app.kubernetes.io/version: v1.2.0
    helm.sh/chart: homepage-2.1.0
  annotations:
    values-checksum: b26f45ae23dfed6328b4a032aed4c21a3a892ab7c6ddd98dd4b51de37079deb5
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
      app.kubernetes.io/instance: homepage
  template:
    metadata:
      annotations:
        
        values-checksum: b26f45ae23dfed6328b4a032aed4c21a3a892ab7c6ddd98dd4b51de37079deb5
      labels:
        app.kubernetes.io/name: homepage
        app.kubernetes.io/instance: homepage
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.2.0
          imagePullPolicy: 
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "192.168.178.94"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: homepage-base-config
              mountPath: /app/config
            - name: homepage-config
              subPath: bookmarks.yaml
              mountPath: /app/config/bookmarks.yaml
            - name: homepage-config
              subPath: docker.yaml
              mountPath: /app/config/docker.yaml
            - name: homepage-config
              subPath: kubernetes.yaml
              mountPath: /app/config/kubernetes.yaml
            - name: homepage-config
              subPath: services.yaml
              mountPath: /app/config/services.yaml
            - name: homepage-config
              subPath: settings.yaml
              mountPath: /app/config/settings.yaml
            - name: homepage-config
              subPath: widgets.yaml
              mountPath: /app/config/widgets.yaml
            - name: logs
              mountPath: /app/config/logs
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
      volumes:
        - name: homepage-base-config
          emptyDir: {}
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir:
            {}
