---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-***REMOVED***-dir
  namespace: kube-system
spec:
  template:
    spec:
      hostPID: true
      hostNetwork: true
      restartPolicy: Never
      containers:
      - name: create-dir
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          mkdir -p /mnt/data/***REMOVED***
          chmod 777 /mnt/data/***REMOVED***
          echo "Directory created on node"
        volumeMounts:
        - name: host-root
          mountPath: /mnt
          mountPropagation: Bidirectional
        securityContext:
          privileged: true
      volumes:
      - name: host-root
        hostPath:
          path: /mnt
      nodeSelector:
        kubernetes.io/hostname: kube-worker2