---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ***REMOVED***-nfs-pv
spec:
  capacity:
    storage: 100Gi  # Adjust size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: 192.168.178.60  # Synology NAS IP
    path: /volume1/Kubernetes/***REMOVED***  # Synology NAS path (note capital K)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ***REMOVED***-nfs-pvc
  namespace: ***REMOVED***
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi