apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ***REMOVED***-pvc
  namespace: ***REMOVED***
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path