---
apiVersion: v1
kind: Namespace
metadata:
  name: ***REMOVED***
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ***REMOVED***
  namespace: ***REMOVED***
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ***REMOVED***
  template:
    metadata:
      labels:
        app: ***REMOVED***
    spec:
      containers:
      - name: ***REMOVED***
        image: ***REMOVED***/***REMOVED***:latest
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: ***REMOVED***-secrets
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ***REMOVED***-secrets
              key: root-password
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: storage
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /***REMOVED***/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /***REMOVED***/health/ready
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: ***REMOVED***-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ***REMOVED***
  namespace: ***REMOVED***
spec:
  selector:
    app: ***REMOVED***
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  type: LoadBalancer
  loadBalancerIP: 192.168.178.95