apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-app-secret
  namespace: default
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: test-app-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: test-app/config
        property: username
    - secretKey: password
      remoteRef:
        key: test-app/config
        property: password
    - secretKey: api_key
      remoteRef:
        key: test-app/config
        property: api_key
